In [1]:
import pandas as pd

df = pd.read_csv("dataset/synthetic_logs.csv")
df.head()

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert

System from which logs are coming

In [2]:
df.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI', 'LegacyCRM'], dtype=object)

In [3]:
df.target_label.unique()

array(['HTTP Status', 'Critical Error', 'Security Alert', 'Error',
       'System Notification', 'Resource Usage', 'User Action',
       'Workflow Error', 'Deprecation Warning'], dtype=object)

In [4]:
df[df.target_label=='System Notification'].sample(10)

,timestamp,source,log_message,target_label,complexity
1187,7/3/2025 3:50,ModernHR,System updated to version 3.3.6.,System Notification,regex
1148,8/13/2025 10:57,ThirdPartyAPI,Backup ended at 2025-08-22 12:30:23.,System Notification,regex
1463,7/29/2025 16:20,ThirdPartyAPI,File data_2288.csv uploaded successfully by us...,System Notification,regex
1406,5/20/2025 11:05,ThirdPartyAPI,Backup started at 2025-09-05 04:17:13.,System Notification,regex
1910,6/8/2025 13:52,ThirdPartyAPI,File data_6245.csv uploaded successfully by us...,System Notification,regex
1902,4/21/2025 17:32,AnalyticsEngine,Backup completed successfully.,System Notification,regex
325,6/2/2025 12:18,ThirdPartyAPI,Backup ended at 2025-07-18 17:06:54.,System Notification,regex
2192,12/28/2025 19:20,ModernCRM,Disk cleanup completed successfully.,System Notification,regex
1542,11/8/2025 20:19,BillingSystem,Disk cleanup completed successfully.,System Notification,regex
1921,11/21/2025 4:16,AnalyticsEngine,System updated to version 1.5.7.,System Notification,regex

Clustering

In [6]:
pip install tf-keras

Collecting tf-keras
  Downloading tf_keras-2.20.1-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: tensorflow<2.21,>=2.20 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tf-keras) (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (2.3.1)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (3.4.0)
Requirement already satisfied: packaging in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (25.0)
Requirement already satisfied: protobuf>=5.28.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (6.33.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (2.32.5)
Requirement already satisfied: setuptools in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (57.4.0)
Requirement already satisfied: six>=1.12.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (2.0.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (1.76.0)
Requirement already satisfied: tensorboard~=2.20.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (3.12.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (1.26.4)
Requirement already satisfied: h5py>=3.11.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (3.15.1)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.20->tf-keras) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.20->tf-keras) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.20->tf-keras) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.20->tf-keras) (2025.11.12)
Requirement already satisfied: markdown>=2.6.8 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorboard~=2.20.0->tensorflow<2.21,>=2.20->tf-keras) (3.10)
Requirement already satisfied: pillow in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorboard~=2.20.0->tensorflow<2.21,>=2.20->tf-keras) (10.4.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorboard~=2.20.0->tensorflow<2.21,>=2.20->tf-keras) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from tensorboard~=2.20.0->tensorflow<2.21,>=2.20->tf-keras) (3.1.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from astunparse>=1.6.0->tensorflow<2.21,>=2.20->tf-keras) (0.45.1)
Requirement already satisfied: rich in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.10.0->tensorflow<2.21,>=2.20->tf-keras) (14.2.0)
Requirement already satisfied: namex in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.10.0->tensorflow<2.21,>=2.20->tf-keras) (0.1.0)
Requirement already satisfied: optree in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from keras>=3.10.0->tensorflow<2.21,>=2.20->tf-keras) (0.18.0)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow<2.21,>=2.20->tf-keras) (2.1.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from rich->keras>=3.10.0->tensorflow<2.21,>=2.20->tf-keras) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from rich->keras>=3.10.0->tensorflow<2.21,>=2.20->tf-keras) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\lenovo\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow<2.21,>=2.20->tf-keras) (0.1.2)
Downloading tf_keras-2.20.1-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------------ --------------------------- 0.5/1.7 MB 2.4 MB/s eta 0:00:01
   ------------------ --------------------- 0.8/1.7 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 2.9 MB/s  0:00:00
Installing collected packages: tf-keras
Successfully installed tf-keras-2.20.1
Note: you may need to restart the kernel to use updated packages.

In [7]:
from sklearn.cluster import DBSCAN
from sentence_transformers import SentenceTransformer

WARNING:tensorflow:From c:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [8]:
model = SentenceTransformer('all-MiniLM-L6-v2')  # Lightweight embedding model
embeddings = model.encode(df['log_message'].tolist())

c:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\LENOVO\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

In [9]:
embeddings[:5]

array([[-0.10293962,  0.03354594, -0.02202607, ...,  0.00457793,
        -0.04259717,  0.00322621],
       [ 0.00804572, -0.03573923,  0.04938739, ...,  0.01538319,
        -0.06230947, -0.02774666],
       [-0.00908224,  0.13003924, -0.05275568, ...,  0.02014104,
        -0.05117098, -0.02930294],
       [-0.09751046,  0.04911299, -0.03977424, ...,  0.02477502,
        -0.03546079, -0.00018598],
       [-0.10468338,  0.05926038, -0.02488499, ...,  0.02502055,
        -0.037193  , -0.0256891 ]], dtype=float32)

In [13]:
from sklearn.cluster import DBSCAN

clustering = DBSCAN(
    eps=0.2,
    min_samples=1,
    metric="cosine"
).fit(embeddings)

df["cluster"] = clustering.labels_

In [15]:
from sklearn.cluster import DBSCAN

clustering = DBSCAN(eps=0.2, min_samples=1, metric="cosine").fit(embeddings)
df["cluster"] = clustering.labels_

In [19]:
print(df.columns.tolist())

['timestamp', 'source', 'log_message', 'target_label', 'complexity', 'cluster']

In [20]:
from collections import defaultdict

clusters = defaultdict(list)

for _, row in df.iterrows():
    clusters[row["cluster"]].append(row["log_message"])

sorted_clusters = dict(
    sorted(clusters.items(), key=lambda x: len(x[1]), reverse=True)
)

In [21]:
print("Clustered Patterns:")
for cluster_id, messages in sorted_clusters.items():
    if len(messages) > 10:
        print(f"\nCluster {cluster_id}:")
        for msg in messages[:5]:
            print(f"  {msg}")

Clustered Patterns:

Cluster 0:
  nova.osapi_compute.wsgi.server [req-b9718cd8-f65e-49cc-8349-6cf7122af137 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" status: 200 len: 1893 time: 0.2675118
  nova.osapi_compute.wsgi.server [req-4895c258-b2f8-488f-a2a3-4fae63982e48 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" HTTP status code -  200 len: 211 time: 0.0968180
  nova.osapi_compute.wsgi.server [req-ee8bc8ba-9265-4280-9215-dbe000a41209 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.2280791
  nova.osapi_compute.wsgi.server [req-f0bffbc3-5ab0-4916-91c1-0a61dd7d4ec2 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" Return code: 200 len: 1874 time: 0.2131531
  nova.osapi_compute.wsgi.server [req-2bf7cfee-a236-42f3-8fb1-96fefab0b302 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.1794369

Cluster 5:
  nova.compute.claims [req-a07ac654-8e81-416d-bfbb-189116b07969 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: bf8c824d-f099-4433-a41e-e3da7578262e] Total memory: 64172 MB, used: 512.00 MB
  nova.compute.claims [req-d6986b54-3735-4a42-9074-0ba7d9717de9 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: af5f7392-f7d4-4298-b647-c98924c64aa1] memory limit: 96258.00 MB, free: 95746.00 MB
  nova.compute.claims [req-72b4858f-049e-49e1-b31e-b562c5018eaf 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 63a0d960-70b6-44c6-b606-491478a5cadf] disk limit not specified, defaulting to unlimited
  nova.compute.claims [req-5c8f52bd-8e3c-41f0-95a5-7861d247cafa 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: d96a117b-0193-4549-bdcc-63b917273d1d] vcpu limit not specified, defaulting to unlimited
  nova.compute.claims [req-d38f479d-9bb9-4276-9688-52607e8fd350 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 95960536-049b-41f6-9049-05fc479b6a7c] disk limit not specified, defaulting to unlimited

Cluster 11:
  User User685 logged out.
  User User395 logged in.
  User User225 logged in.
  User User494 logged out.
  User User900 logged in.

Cluster 13:
  Backup started at 2025-05-14 07:06:55.
  Backup started at 2025-02-15 20:00:19.
  Backup ended at 2025-08-08 13:06:23.
  Backup started at 2025-11-14 08:27:43.
  Backup started at 2025-12-09 10:19:11.

Cluster 7:
  Multiple bad login attempts detected on user 8538 account
  Multiple login failures occurred on user 9052 account
  User 7153 made multiple incorrect login attempts
  User 8300 made multiple incorrect login attempts
  Multiple login failures were detected for user 6373

Cluster 8:
  Backup completed successfully.
  Backup completed successfully.
  Backup completed successfully.
  Backup completed successfully.
  Backup completed successfully.

Cluster 21:
  System updated to version 3.9.1.
  System updated to version 5.5.4.
  System updated to version 4.7.4.
  System updated to version 3.7.7.
  System updated to version 2.6.2.

Cluster 3:
  Shard 6 replication task ended in failure
  Data replication task for shard 14 did not complete
  Data replication task failed for shard 17
  Replication of data to shard 14 failed
  Data replication task for shard 6 did not complete

Cluster 4:
  File data_6169.csv uploaded successfully by user User953.
  File data_3847.csv uploaded successfully by user User175.
  File data_7366.csv uploaded successfully by user User282.
  File data_1206.csv uploaded successfully by user User359.
  File data_1503.csv uploaded successfully by user User151.

Cluster 17:
  Denied access attempt on restricted account Account2682
  Unauthorized login attempt on protected account Account5030
  Account Account9437 blocked due to failed login
  Account Account7999 access denied due to login failure
  Invalid login attempt made on secured account Account7864

Cluster 6:
  Critical system unit error: unit ID Component55
  System component malfunction: component ID Component79
  Critical system element is down: element ID Component96
  Essential system part malfunction: part ID Component6
  Failure occurred in critical system component: component ID Component92

Cluster 32:
  Disk cleanup completed successfully.
  Disk cleanup completed successfully.
  Disk cleanup completed successfully.
  Disk cleanup completed successfully.
  Disk cleanup completed successfully.

Cluster 16:
  System reboot initiated by user User243.
  System reboot initiated by user User471.
  System reboot initiated by user User216.
  System reboot initiated by user User639.
  System reboot initiated by user User819.

Cluster 20:
  User 7662 tried to bypass API security measures
  User 2367 failed to provide valid API access credentials
  User 3569 made an unauthorized API request
  Unauthorized user 2968 tried to access restricted API
  User 2186 attempted to access API without proper authorization

Cluster 9:
  Account with ID 5351 created by User634.
  Account with ID 7813 created by User373.
  Account with ID 9827 created by User965.
  Account with ID 2520 created by User546.
  Account with ID 2300 created by User964.

Cluster 1:
  Email service experiencing issues with sending
  Email server encountered a sending fault
  Mail service encountered a delivery glitch
  Service disruption caused by email sending error
  Email system had a problem sending emails

Cluster 10:
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=512MB phys_disk=15GB used_disk=0GB total_vcpus=16 used_vcpus=0 pci_stats=[]
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Total usable vcpus: 16, total allocated vcpus: 0
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]

Cluster 34:
  Abnormal behavior found on server 10, possible security threat
  Security alert: suspicious activity on server 1
  Anomalous activity identified on server 23, security review recommended
  Server 27 experienced potential security incident, review required
  Server 36 experienced potential security incident, review required

Cluster 14:
  Detection of multiple disk faults in RAID setup
  RAID array suffered multiple hard drive failures
  RAID array experienced multiple disk crashes
  Multiple hard drive issues in RAID configuration found
  Identification of multiple faulty disks in RAID array

Cluster 52:
  Service health check was not successful because of SSL certificate validation failures.
  Invalid SSL certificate resulted in a failed service health check.
  Service health check failure was due to an invalid or improperly configured SSL certificate.
  An issue with the SSL certificate caused the service health check to fail.
  Service health check failure was caused by an expired SSL certificate.

Cluster 53:
  Module X experienced an invalid data format issue
  Input format mismatch occurred in module X
  Module X reported an error in input format validation
  Module X failed to process input due to formatting error
  Input data format in module X was invalid or corrupted

Cluster 18:
  Boot process terminated unexpectedly due to kernel issue
  System encountered kernel panic during initialization phase
  Boot process was stopped by kernel malfunction
  System encountered kernel failure during bootup sequence
  Boot sequence failed due to kernel panic

Cluster 25:
  System configuration is no longer valid
  Configuration is corrupted throughout the system
  Cross-system configuration failure occurred
  System configuration is experiencing errors
  Configuration malfunction is system-wide

Cluster 42:
  User 5127 has escalated admin privileges without authorization
  User 9745 has escalated to admin level
  User 8483 escalated privileges to admin level
  User 1987 has escalated to admin level
  User 8395 escalated privileges to admin level

Cluster 59:
  Potential security threat: Admin privilege escalation for user 5130
  Admin privilege escalation alert for user 2893
  Admin privilege escalation alert for user 8532
  Potential security threat: Admin privilege escalation for user 1554
  Warning: Potential admin privilege escalation for user 5720

Cluster 26:
  Privilege elevation detected for user 5038
  Elevation of admin privileges detected for user 6137
  Elevation of admin privileges detected for user 4907
  User 6069 has been granted elevated admin privileges
  Admin privilege elevation warning for user 7574

In [22]:
print("Clustered Patterns:")
for cluster_id, messages in sorted_clusters.items():
    if len(messages) > 10:
        print(f"Cluster {cluster_id}:")
        for msg in messages[:5]:
            print(f"  {msg}")

Clustered Patterns:
Cluster 0:
  nova.osapi_compute.wsgi.server [req-b9718cd8-f65e-49cc-8349-6cf7122af137 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" status: 200 len: 1893 time: 0.2675118
  nova.osapi_compute.wsgi.server [req-4895c258-b2f8-488f-a2a3-4fae63982e48 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" HTTP status code -  200 len: 211 time: 0.0968180
  nova.osapi_compute.wsgi.server [req-ee8bc8ba-9265-4280-9215-dbe000a41209 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.2280791
  nova.osapi_compute.wsgi.server [req-f0bffbc3-5ab0-4916-91c1-0a61dd7d4ec2 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" Return code: 200 len: 1874 time: 0.2131531
  nova.osapi_compute.wsgi.server [req-2bf7cfee-a236-42f3-8fb1-96fefab0b302 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.1794369
Cluster 5:
  nova.compute.claims [req-a07ac654-8e81-416d-bfbb-189116b07969 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: bf8c824d-f099-4433-a41e-e3da7578262e] Total memory: 64172 MB, used: 512.00 MB
  nova.compute.claims [req-d6986b54-3735-4a42-9074-0ba7d9717de9 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: af5f7392-f7d4-4298-b647-c98924c64aa1] memory limit: 96258.00 MB, free: 95746.00 MB
  nova.compute.claims [req-72b4858f-049e-49e1-b31e-b562c5018eaf 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 63a0d960-70b6-44c6-b606-491478a5cadf] disk limit not specified, defaulting to unlimited
  nova.compute.claims [req-5c8f52bd-8e3c-41f0-95a5-7861d247cafa 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: d96a117b-0193-4549-bdcc-63b917273d1d] vcpu limit not specified, defaulting to unlimited
  nova.compute.claims [req-d38f479d-9bb9-4276-9688-52607e8fd350 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 95960536-049b-41f6-9049-05fc479b6a7c] disk limit not specified, defaulting to unlimited
Cluster 11:
  User User685 logged out.
  User User395 logged in.
  User User225 logged in.
  User User494 logged out.
  User User900 logged in.
Cluster 13:
  Backup started at 2025-05-14 07:06:55.
  Backup started at 2025-02-15 20:00:19.
  Backup ended at 2025-08-08 13:06:23.
  Backup started at 2025-11-14 08:27:43.
  Backup started at 2025-12-09 10:19:11.
Cluster 7:
  Multiple bad login attempts detected on user 8538 account
  Multiple login failures occurred on user 9052 account
  User 7153 made multiple incorrect login attempts
  User 8300 made multiple incorrect login attempts
  Multiple login failures were detected for user 6373
Cluster 8:
  Backup completed successfully.
  Backup completed successfully.
  Backup completed successfully.
  Backup completed successfully.
  Backup completed successfully.
Cluster 21:
  System updated to version 3.9.1.
  System updated to version 5.5.4.
  System updated to version 4.7.4.
  System updated to version 3.7.7.
  System updated to version 2.6.2.
Cluster 3:
  Shard 6 replication task ended in failure
  Data replication task for shard 14 did not complete
  Data replication task failed for shard 17
  Replication of data to shard 14 failed
  Data replication task for shard 6 did not complete
Cluster 4:
  File data_6169.csv uploaded successfully by user User953.
  File data_3847.csv uploaded successfully by user User175.
  File data_7366.csv uploaded successfully by user User282.
  File data_1206.csv uploaded successfully by user User359.
  File data_1503.csv uploaded successfully by user User151.
Cluster 17:
  Denied access attempt on restricted account Account2682
  Unauthorized login attempt on protected account Account5030
  Account Account9437 blocked due to failed login
  Account Account7999 access denied due to login failure
  Invalid login attempt made on secured account Account7864
Cluster 6:
  Critical system unit error: unit ID Component55
  System component malfunction: component ID Component79
  Critical system element is down: element ID Component96
  Essential system part malfunction: part ID Component6
  Failure occurred in critical system component: component ID Component92
Cluster 32:
  Disk cleanup completed successfully.
  Disk cleanup completed successfully.
  Disk cleanup completed successfully.
  Disk cleanup completed successfully.
  Disk cleanup completed successfully.
Cluster 16:
  System reboot initiated by user User243.
  System reboot initiated by user User471.
  System reboot initiated by user User216.
  System reboot initiated by user User639.
  System reboot initiated by user User819.
Cluster 20:
  User 7662 tried to bypass API security measures
  User 2367 failed to provide valid API access credentials
  User 3569 made an unauthorized API request
  Unauthorized user 2968 tried to access restricted API
  User 2186 attempted to access API without proper authorization
Cluster 9:
  Account with ID 5351 created by User634.
  Account with ID 7813 created by User373.
  Account with ID 9827 created by User965.
  Account with ID 2520 created by User546.
  Account with ID 2300 created by User964.
Cluster 1:
  Email service experiencing issues with sending
  Email server encountered a sending fault
  Mail service encountered a delivery glitch
  Service disruption caused by email sending error
  Email system had a problem sending emails
Cluster 10:
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=512MB phys_disk=15GB used_disk=0GB total_vcpus=16 used_vcpus=0 pci_stats=[]
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Total usable vcpus: 16, total allocated vcpus: 0
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
  nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
Cluster 34:
  Abnormal behavior found on server 10, possible security threat
  Security alert: suspicious activity on server 1
  Anomalous activity identified on server 23, security review recommended
  Server 27 experienced potential security incident, review required
  Server 36 experienced potential security incident, review required
Cluster 14:
  Detection of multiple disk faults in RAID setup
  RAID array suffered multiple hard drive failures
  RAID array experienced multiple disk crashes
  Multiple hard drive issues in RAID configuration found
  Identification of multiple faulty disks in RAID array
Cluster 52:
  Service health check was not successful because of SSL certificate validation failures.
  Invalid SSL certificate resulted in a failed service health check.
  Service health check failure was due to an invalid or improperly configured SSL certificate.
  An issue with the SSL certificate caused the service health check to fail.
  Service health check failure was caused by an expired SSL certificate.
Cluster 53:
  Module X experienced an invalid data format issue
  Input format mismatch occurred in module X
  Module X reported an error in input format validation
  Module X failed to process input due to formatting error
  Input data format in module X was invalid or corrupted
Cluster 18:
  Boot process terminated unexpectedly due to kernel issue
  System encountered kernel panic during initialization phase
  Boot process was stopped by kernel malfunction
  System encountered kernel failure during bootup sequence
  Boot sequence failed due to kernel panic
Cluster 25:
  System configuration is no longer valid
  Configuration is corrupted throughout the system
  Cross-system configuration failure occurred
  System configuration is experiencing errors
  Configuration malfunction is system-wide
Cluster 42:
  User 5127 has escalated admin privileges without authorization
  User 9745 has escalated to admin level
  User 8483 escalated privileges to admin level
  User 1987 has escalated to admin level
  User 8395 escalated privileges to admin level
Cluster 59:
  Potential security threat: Admin privilege escalation for user 5130
  Admin privilege escalation alert for user 2893
  Admin privilege escalation alert for user 8532
  Potential security threat: Admin privilege escalation for user 1554
  Warning: Potential admin privilege escalation for user 5720
Cluster 26:
  Privilege elevation detected for user 5038
  Elevation of admin privileges detected for user 6137
  Elevation of admin privileges detected for user 4907
  User 6069 has been granted elevated admin privileges
  Admin privilege elevation warning for user 7574